### ISSUE TITLE
The stripping of spaces in a code span only happens if the space is on both sides of the string

### ISSUE THREAD

**Issue by lostenderman** [lostenderman/markdown#15] opened 2022-12-12 20:16 UTC
See <https://spec.commonmark.org/0.30/#example-332>

**Comment by Witiko** [comment] 2022-12-30 23:47
This issue is a duplicate of issue #107.

**Comment by lostenderman** [comment] 2023-01-03 21:50
Not closing after pull #111, example 332 fails.

Spaces are not preserved in the output.

**Comment by Witiko** [comment] 2023-01-04 00:08
The corresponding unit test is `testfiles/CommonMark_0.30/code_spans/005.test`:

``````````` md
%   ---RESULT--- "example": 332,
%   
%   <p><code> a</code></p>
%   
%   ---\RESULT---

<<<
` a`
>>>
documentBegin
codeSpan:  a
documentEnd
```````````

Here is the result of running `git checkout commonmark; cd tests; ./test.sh "testfiles/CommonMark_0.30/code_spans/005.test"`:

```````````
Testfile testfiles/CommonMark_0.30/code_spans/005.test
  Format templates/plain/
    Template templates/plain/input.tex.m4
      Command luatex                                   --interaction=nonstopmode  test.tex
*** test-expected.log	2023-01-04 01:06:43.136867788 +0100
--- test-actual.log	2023-01-04 01:06:49.086824263 +0100
***************
*** 1,3 ****
  documentBegin
! codeSpan:  a
  documentEnd
--- 1,3 ----
  documentBegin
! codeSpan: a
  documentEnd
```````````

The issue seems related to the PEG patterns for parsing code spans ([1][], [2][]), which use the rules for [Gruber's Markdown][3] rather than [CommonMark][4].

 [1]: https://github.com/Witiko/markdown/blob/9530198735bec755abe75b9f93f8c664d57aa6f8/markdown.dtx#L21636-L21663
 [2]: https://github.com/Witiko/markdown/blob/9530198735bec755abe75b9f93f8c664d57aa6f8/markdown.dtx#L22350
 [3]: https://daringfireball.net/projects/markdown/syntax#code
 [4]: https://spec.commonmark.org/0.30/#code-spans

**Closed** 2023-05-04 18:08 UTC
Labels: code spans
