### ISSUE TITLE
Interior spaces in a code span should not be collapsed

### ISSUE THREAD

**Issue by lostenderman** [lostenderman/markdown#17] opened 2022-12-12 20:19 UTC
See <https://spec.commonmark.org/0.30/#example-337>

**Comment by Witiko** [comment] 2022-12-30 23:46
This issue is a duplicate of issue #107.

**Comment by lostenderman** [comment] 2023-01-03 21:43
Not closing after pull #111, example 337 fails.

Trailing spaces are not preserved in the output.

**Comment by Witiko** [comment] 2023-01-03 23:58
@lostenderman TeX will always fold trailing spaces at the end of a line. We will likely need to delete the unit test similarly to https://github.com/lostenderman/markdown/issues/37.

**Closed** 2023-05-04 18:09 UTC
Labels: code spans
