### ISSUE TITLE
A backslash at the end of the line is a hard line break

### ISSUE THREAD

**Issue by lostenderman** [lostenderman/markdown#11] opened 2022-12-12 20:11 UTC
See <https://spec.commonmark.org/0.30/#example-16>

**Comment by Witiko** [comment] 2022-12-14 11:55
Closing issue https://github.com/Witiko/markdown/issues/210 closes this issue.

**Comment by Witiko** [comment] 2022-12-30 19:16
This issue is a duplicate of issue #38.

**Closed** 2023-01-28 15:01 UTC
Labels: backslash escapes
